# Generated by Django 4.2.1 on 2023-05-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_image_college_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField(max_length=100)),
                ('eventType', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college_user')),
            ],
        ),
    ]
