# Generated by Django 4.2.1 on 2023-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_college_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_events',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
